const BASE_DEFAULT_HOTKEYS = [
  // Annotation Controls
  {
    id: 100,
    section: "annotation",
    element: "annotation:submit",
    label: "Submit Annotation",
    key: "ctrl+enter",
    description: "Submit the current annotation",
    active: true,
  },
  {
    id: 200,
    section: "annotation",
    element: "annotation:skip",
    label: "Skip Task",
    key: "ctrl+space",
    description: "Skip the current task",
    active: true,
  },
  {
    id: 300,
    section: "annotation",
    element: "annotation:undo",
    label: "Undo",
    key: "ctrl+z",
    description: "Undo last action",
    active: true,
  },
  {
    id: 400,
    section: "annotation",
    element: "annotation:redo",
    label: "Redo",
    key: "ctrl+shift+z",
    description: "Redo previously undone action",
    active: true,
  },

  // Data Manager
  {
    id: 500,
    section: "data_manager",
    element: "dm.focus-previous",
    label: "Focus Previous Task",
    key: "shift+up",
    description: "Move focus to the previous task",
    active: true,
  },
  {
    id: 600,
    section: "data_manager",
    element: "dm.focus-next",
    label: "Focus Next Task",
    key: "shift+down",
    description: "Move focus to the next task",
    active: true,
  },
  {
    id: 700,
    section: "data_manager",
    element: "dm.close-labeling",
    label: "Focus Closed Task",
    key: "shift+left",
    description: "Focus on the closed task column",
    active: true,
  },
  {
    id: 800,
    section: "data_manager",
    element: "dm.open-labeling",
    label: "Focus Open Task",
    key: "shift+right",
    description: "Focus on the open task column",
    active: true,
  },
  {
    id: 900,
    section: "data_manager",
    element: "dm.toggle-bulk-sidebar-minimization",
    label: "Toggle Bulk Sidebar",
    key: "shift+.",
    description: "Minimize or expand bulk actions sidebar",
    active: true,
  },

  // Region Management
  {
    id: 1100,
    section: "regions",
    element: "region:delete-all",
    label: "Delete All Regions",
    key: "ctrl+backspace",
    description: "Remove all regions",
    active: true,
  },
  {
    id: 1200,
    section: "regions",
    element: "region:focus",
    label: "Focus First Region",
    key: "enter",
    description: "Move focus to the first focusable region",
    active: true,
  },
  {
    id: 1300,
    section: "regions",
    element: "region:relation",
    label: "Create Region Relation",
    key: "alt+r",
    description: "Create a relation between selected regions",
    active: true,
  },
  {
    id: 1400,
    section: "regions",
    element: "region:visibility",
    label: "Toggle Region Visibility",
    key: "alt+h",
    description: "Show or hide the selected region",
    active: true,
  },
  {
    id: 1500,
    section: "regions",
    element: "region:visibility-all",
    label: "Toggle All Region Visibility",
    key: "ctrl+h",
    description: "Show or hide all regions",
    active: true,
  },
  {
    id: 1600,
    section: "regions",
    element: "region:lock",
    label: "Lock Region",
    key: "alt+l",
    description: "Lock or unlock the selected region",
    active: true,
  },
  {
    id: 1700,
    section: "regions",
    element: "region:meta",
    label: "Edit Region Metadata",
    key: "alt+m",
    description: "Edit metadata for selected region",
    active: true,
  },
  {
    id: 1800,
    section: "regions",
    element: "region:unselect",
    label: "Unselect Region",
    key: "u",
    description: "Deselect the currently selected region",
    active: true,
  },
  {
    id: 1900,
    section: "regions",
    element: "region:exit",
    label: "Exit Region Mode",
    key: "escape",
    description: "Exit relation mode and unselect region",
    active: true,
  },
  {
    id: 2000,
    section: "regions",
    element: "region:delete",
    label: "Delete Selected Region",
    key: "backspace",
    description: "Delete currently selected region",
    active: true,
  },
  {
    id: 2100,
    section: "regions",
    element: "region:cycle",
    label: "Cycle Regions",
    key: "alt+.",
    description: "Cycle through all regions",
    active: true,
  },
  {
    id: 2200,
    section: "regions",
    element: "region:duplicate",
    label: "Duplicate Region",
    key: "ctrl+d",
    description: "Create a copy of the selected region",
    active: true,
  },
  {
    id: 2300,
    section: "regions",
    element: "segment:delete",
    label: "Delete Segment",
    key: "delete",
    description: "Delete selected segment",
    active: true,
  },

  // Editor - Audio Controls
  {
    id: 2400,
    section: "audio",
    element: "audio:back",
    label: "Rewind 1 Second",
    key: "ctrl+b",
    description: "Rewind the audio by 1 second",
    active: true,
  },
  {
    id: 2500,
    section: "audio",
    element: "audio:playpause",
    label: "Play / Pause Audio",
    key: "ctrl+p",
    description: "Toggle audio playback",
    active: true,
  },
  {
    id: 2600,
    section: "audio",
    element: "audio:step-backward",
    label: "Step Back",
    key: "alt+a",
    description: "Step back one frame",
    active: true,
  },
  {
    id: 2700,
    section: "audio",
    element: "audio:step-forward",
    label: "Step Forward",
    key: "alt+d",
    description: "Step forward one frame",
    active: true,
  },

  // Editor - Video Controls
  {
    id: 2800,
    section: "video",
    element: "media:playpause",
    label: "Play / Pause Video",
    key: "ctrl+alt+space",
    description: "Toggle video playback",
    active: true,
  },
  {
    id: 2900,
    section: "video",
    element: "media:step-backward",
    label: "Step Back",
    key: "alt+left",
    description: "Step one frame backward",
    active: true,
  },
  {
    id: 3000,
    section: "video",
    element: "media:step-forward",
    label: "Step Forward",
    key: "alt+right",
    description: "Step one frame forward",
    active: true,
  },
  {
    id: 3100,
    section: "video",
    element: "video:keyframe-backward",
    label: "Previous Keyframe",
    key: "ctrl+alt+left",
    description: "Jump to previous keyframe",
    active: true,
  },
  {
    id: 3200,
    section: "video",
    element: "video:keyframe-forward",
    label: "Next Keyframe",
    key: "ctrl+alt+right",
    description: "Jump to next keyframe",
    active: true,
  },
  {
    id: 3300,
    section: "video",
    element: "video:backward",
    label: "Seek Backward",
    key: "alt+left",
    description: "Seek video backward",
    active: true,
  },
  {
    id: 3400,
    section: "video",
    element: "video:rewind",
    label: "First Frame",
    key: "shift+ctrl+alt+left",
    description: "Jump to first frame",
    active: true,
  },
  {
    id: 3500,
    section: "video",
    element: "video:forward",
    label: "Seek Forward",
    key: "shift+alt+right",
    description: "Seek video forward",
    active: true,
  },
  {
    id: 3600,
    section: "video",
    element: "video:fastforward",
    label: "Last Frame",
    key: "shift+ctrl+alt+right",
    description: "Jump to last frame",
    active: true,
  },
  {
    id: 3700,
    section: "video",
    element: "video:hop-backward",
    label: "Hop Backward",
    key: "shift+alt+left",
    description: "Hop backward quickly",
    active: true,
  },
  {
    id: 3800,
    section: "video",
    element: "video:hop-forward",
    label: "Hop Forward",
    key: "shift+alt+right",
    description: "Hop forward quickly",
    active: true,
  },

  // Editor - Time Series Controls
  {
    id: 3900,
    section: "timeseries",
    element: "ts:grow-left",
    label: "Extend Left",
    key: "left",
    description: "Extend the region to the left",
    active: true,
  },
  {
    id: 4000,
    section: "timeseries",
    element: "ts:grow-right",
    label: "Extend Right",
    key: "right",
    description: "Extend the region to the right",
    active: true,
  },
  {
    id: 4100,
    section: "timeseries",
    element: "ts:shrink-left",
    label: "Shrink Left",
    key: "alt+left",
    description: "Shrink the region from the left",
    active: true,
  },
  {
    id: 4200,
    section: "timeseries",
    element: "ts:shrink-right",
    label: "Shrink Right",
    key: "alt+right",
    description: "Shrink the region from the right",
    active: true,
  },
  {
    id: 4300,
    section: "timeseries",
    element: "ts:grow-left-large",
    label: "Extend Left (Large)",
    key: "shift+left",
    description: "Extend region left significantly",
    active: true,
  },
  {
    id: 4400,
    section: "timeseries",
    element: "ts:grow-right-large",
    label: "Extend Right (Large)",
    key: "shift+right",
    description: "Extend region right significantly",
    active: true,
  },
  {
    id: 4500,
    section: "timeseries",
    element: "ts:shrink-left-large",
    label: "Shrink Left (Large)",
    key: "shift+alt+left",
    description: "Shrink region from left significantly",
    active: true,
  },
  {
    id: 4600,
    section: "timeseries",
    element: "ts:shrink-right-large",
    label: "Shrink Right (Large)",
    key: "shift+alt+right",
    description: "Shrink region from right significantly",
    active: true,
  },

  // Image Gallery Controls
  {
    id: 4700,
    section: "image_gallery",
    element: "image:prev",
    label: "Previous Image",
    key: "ctrl+left",
    description: "View previous image",
    active: true,
  },
  {
    id: 4800,
    section: "image_gallery",
    element: "image:next",
    label: "Next Image",
    key: "ctrl+right",
    description: "View next image",
    active: true,
  },

  {
    id: 5000,
    section: "tools",
    element: "tool:zoom-in",
    label: "Zoom In",
    key: "ctrl+plus",
    description: "Zoom in on the image",
    active: true,
  },
  {
    id: 5100,
    section: "tools",
    element: "tool:pan-image",
    label: "Pan Image",
    key: "H",
    description: "Pan around the image",
    active: true,
  },
  {
    id: 5200,
    section: "tools",
    element: "tool:zoom-to-fit",
    label: "Zoom to Fit",
    key: "shift+1",
    description: "Zoom to fit the full image in view",
    active: true,
  },
  {
    id: 5300,
    section: "tools",
    element: "tool:zoom-to-actual",
    label: "Zoom to 100%",
    key: "shift+2",
    description: "Zoom to actual image size (100%)",
    active: true,
  },
  {
    id: 5400,
    section: "tools",
    element: "tool:zoom-out",
    label: "Zoom Out",
    key: "ctrl+minus",
    description: "Zoom out of the image",
    active: true,
  },
  {
    id: 5401,
    section: "tools",
    element: "tool:move",
    label: "Move Tool",
    key: "V",
    description: "Select the move tool to reposition annotations",
    active: true,
  },
  {
    id: 5402,
    section: "tools",
    element: "tool:brush",
    label: "Brush Tool",
    key: "B",
    description: "Select the brush tool",
    active: true,
  },

  {
    id: 5500,
    section: "tools",
    element: "tool:ellipse",
    label: "Ellipse Tool",
    key: "O",
    description: "Select the ellipse tool",
    active: true,
  },
  {
    id: 5600,
    section: "tools",
    element: "tool:eraser",
    label: "Eraser Tool",
    key: "E",
    description: "Select the eraser tool",
    active: true,
  },
  {
    id: 5700,
    section: "tools",
    element: "tool:auto-detect",
    label: "Auto Detect",
    key: "M",
    description: "Use the auto-detect tool to automatically suggest regions",
    active: true,
  },
  {
    id: 5900,
    section: "tools",
    element: "tool:key-point",
    label: "Key Point Tool",
    key: "K",
    description: "Select the key point annotation tool",
    active: true,
  },
  {
    id: 6000,
    section: "tools",
    element: "tool:magic-wand",
    label: "Magic Wand",
    key: "W",
    description: "Select the magic wand tool for smart region selection",
    active: true,
  },
  {
    id: 6100,
    section: "tools",
    element: "tool:polygon",
    label: "Polygon Tool",
    key: "P",
    description: "Select the polygon annotation tool",
    active: true,
  },
  {
    id: 6200,
    section: "tools",
    element: "tool:rect",
    label: "Rectangle Tool",
    key: "R",
    description: "Select the rectangle annotation tool",
    active: true,
  },
  {
    id: 6201,
    section: "tools",
    element: "tool:rect-3point",
    label: "3-Point Rectangle",
    key: "shift+R",
    description: "Draw a rotated rectangle using 3-point selection",
    active: true,
  },

  {
    id: 6300,
    section: "tools",
    element: "tool:rotate-left",
    label: "Rotate Left",
    key: "alt+left",
    description: "Rotate the image 90° to the left",
    active: true,
  },
  {
    id: 6400,
    section: "tools",
    element: "tool:rotate-right",
    label: "Rotate Right",
    key: "alt+right",
    description: "Rotate the image 90° to the right",
    active: true,
  },
  {
    id: 6700,
    section: "tools",
    element: "tool:decrease-tool",
    label: "Decrease Tool Size",
    key: "[",
    description: "Decrease tool size",
    active: true,
  },
  {
    id: 6800,
    section: "tools",
    element: "tool:increase-tool",
    label: "Increase Tool Size",
    key: "]",
    description: "Increase tool size",
    active: true,
  },

  // Paragraph Navigation
  {
    id: 6900,
    section: "paragraphs",
    element: "phrases:next-phrase",
    label: "Next Phrase",
    key: "ctrl+down",
    description: "Navigate to the next phrase in paragraph view",
    active: true,
  },
  {
    id: 7000,
    section: "paragraphs",
    element: "phrases:previous-phrase",
    label: "Previous Phrase",
    key: "ctrl+up",
    description: "Navigate to the previous phrase in paragraph view",
    active: true,
  },
  {
    id: 7100,
    section: "paragraphs",
    element: "phrases:select_all_annotate",
    label: "Select All and Annotate",
    key: "ctrl+shift+a",
    description: "Select all text in current phrase and create annotation",
    active: true,
  },
  {
    id: 7200,
    section: "paragraphs",
    element: "phrases:next-region",
    label: "Next Region in Phrase",
    key: "ctrl+right",
    description: "Navigate to the next region within current phrase",
    active: true,
  },
  {
    id: 7300,
    section: "paragraphs",
    element: "phrases:previous-region",
    label: "Previous Region in Phrase",
    key: "ctrl+left",
    description: "Navigate to the previous region within current phrase",
    active: true,
  },
];

const HOTKEY_TRANSLATIONS = {
  "annotation:submit": { label: "提交标注", description: "提交当前标注结果" },
  "annotation:skip": { label: "跳过任务", description: "跳过当前任务" },
  "annotation:undo": { label: "撤销", description: "撤销上一次操作" },
  "annotation:redo": { label: "重做", description: "重做上一次撤销的操作" },
  "dm.focus-previous": { label: "聚焦上一条任务", description: "将焦点移动到上一条任务" },
  "dm.focus-next": { label: "聚焦下一条任务", description: "将焦点移动到下一条任务" },
  "dm.close-labeling": { label: "聚焦已关闭任务", description: "将焦点移动到已关闭任务列" },
  "dm.open-labeling": { label: "聚焦未关闭任务", description: "将焦点移动到未关闭任务列" },
  "dm.toggle-bulk-sidebar-minimization": { label: "切换批量侧栏", description: "收起或展开批量操作侧栏" },
  "region:delete-all": { label: "删除全部区域", description: "移除所有区域" },
  "region:focus": { label: "聚焦首个区域", description: "将焦点移动到第一个可聚焦区域" },
  "region:relation": { label: "创建区域关系", description: "为选中区域创建关系" },
  "region:visibility": { label: "切换区域可见性", description: "显示或隐藏选中区域" },
  "region:visibility-all": { label: "切换全部区域可见性", description: "显示或隐藏全部区域" },
  "region:lock": { label: "锁定区域", description: "锁定或解锁选中区域" },
  "region:meta": { label: "编辑区域元数据", description: "编辑选中区域的元数据" },
  "region:unselect": { label: "取消选择区域", description: "取消当前选中的区域" },
  "region:exit": { label: "退出区域模式", description: "退出关系模式并取消选中区域" },
  "region:delete": { label: "删除选中区域", description: "删除当前选中的区域" },
  "region:cycle": { label: "循环切换区域", description: "在所有区域之间循环切换" },
  "region:duplicate": { label: "复制区域", description: "创建选中区域的副本" },
  "segment:delete": { label: "删除分段", description: "删除选中的分段" },
  "audio:back": { label: "后退 1 秒", description: "将音频回退 1 秒" },
  "audio:playpause": { label: "播放/暂停音频", description: "切换音频播放状态" },
  "audio:step-backward": { label: "后退一帧", description: "向后移动一帧" },
  "audio:step-forward": { label: "前进一帧", description: "向前移动一帧" },
  "media:playpause": { label: "播放/暂停视频", description: "切换视频播放状态" },
  "media:step-backward": { label: "后退一帧", description: "向后移动一帧" },
  "media:step-forward": { label: "前进一帧", description: "向前移动一帧" },
  "video:keyframe-backward": { label: "上一个关键帧", description: "跳转到上一个关键帧" },
  "video:keyframe-forward": { label: "下一个关键帧", description: "跳转到下一个关键帧" },
  "video:backward": { label: "向后跳转", description: "向后定位视频" },
  "video:rewind": { label: "第一帧", description: "跳转到第一帧" },
  "video:forward": { label: "向前跳转", description: "向前定位视频" },
  "video:fastforward": { label: "最后一帧", description: "跳转到最后一帧" },
  "video:hop-backward": { label: "快速后跳", description: "快速向后跳转" },
  "video:hop-forward": { label: "快速前跳", description: "快速向前跳转" },
  "ts:grow-left": { label: "向左扩展", description: "将区域向左扩展" },
  "ts:grow-right": { label: "向右扩展", description: "将区域向右扩展" },
  "ts:shrink-left": { label: "左侧收缩", description: "从左侧收缩区域" },
  "ts:shrink-right": { label: "右侧收缩", description: "从右侧收缩区域" },
  "ts:grow-left-large": { label: "大幅向左扩展", description: "显著向左扩展区域" },
  "ts:grow-right-large": { label: "大幅向右扩展", description: "显著向右扩展区域" },
  "ts:shrink-left-large": { label: "大幅左侧收缩", description: "从左侧显著收缩区域" },
  "ts:shrink-right-large": { label: "大幅右侧收缩", description: "从右侧显著收缩区域" },
  "image:prev": { label: "上一张图片", description: "查看上一张图片" },
  "image:next": { label: "下一张图片", description: "查看下一张图片" },
  "tool:zoom-in": { label: "放大", description: "放大图片" },
  "tool:pan-image": { label: "平移图片", description: "在图片上平移查看" },
  "tool:zoom-to-fit": { label: "适应窗口", description: "缩放到完整图片适应当前视图" },
  "tool:zoom-to-actual": { label: "缩放到 100%", description: "按图片实际大小显示（100%）" },
  "tool:zoom-out": { label: "缩小", description: "缩小图片" },
  "tool:move": { label: "移动工具", description: "选择移动工具以重新放置标注" },
  "tool:brush": { label: "画笔工具", description: "选择画笔工具" },
  "tool:ellipse": { label: "椭圆工具", description: "选择椭圆工具" },
  "tool:eraser": { label: "橡皮擦工具", description: "选择橡皮擦工具" },
  "tool:auto-detect": { label: "自动检测", description: "使用自动检测工具自动建议区域" },
  "tool:key-point": { label: "关键点工具", description: "选择关键点标注工具" },
  "tool:magic-wand": { label: "魔棒工具", description: "选择魔棒工具以进行智能区域选择" },
  "tool:polygon": { label: "多边形工具", description: "选择多边形标注工具" },
  "tool:rect": { label: "矩形工具", description: "选择矩形标注工具" },
  "tool:rect-3point": { label: "三点矩形", description: "通过三点选择绘制旋转矩形" },
  "tool:rotate-left": { label: "向左旋转", description: "将图片向左旋转 90°" },
  "tool:rotate-right": { label: "向右旋转", description: "将图片向右旋转 90°" },
  "tool:decrease-tool": { label: "减小工具大小", description: "减小工具大小" },
  "tool:increase-tool": { label: "增大工具大小", description: "增大工具大小" },
  "phrases:next-phrase": { label: "下一句", description: "在段落视图中跳转到下一句" },
  "phrases:previous-phrase": { label: "上一句", description: "在段落视图中跳转到上一句" },
  "phrases:select_all_annotate": { label: "全选并标注", description: "选中当前句子的全部文本并创建标注" },
  "phrases:next-region": { label: "句内下一区域", description: "跳转到当前句子中的下一个区域" },
  "phrases:previous-region": { label: "句内上一区域", description: "跳转到当前句子中的上一个区域" },
};

const BASE_HOTKEY_SECTIONS = [
  {
    id: "annotation",
    title: "标注操作",
    description: "用于提交、跳过、撤销、重做等常见标注操作的快捷键",
  },

  {
    id: "data_manager",
    title: "数据管理",
    description: "用于在项目数据管理页中浏览和管理任务的快捷键",
  },

  {
    id: "regions",
    title: "区域管理",
    description: "用于创建、选择和操作标注区域的快捷键",
  },

  {
    id: "tools",
    title: "工具",
    description: "用于图片标注时控制工具面板的快捷键",
  },

  {
    id: "audio",
    title: "音频控制",
    description: "用于控制音频播放和导航的快捷键",
  },
  {
    id: "video",
    title: "视频控制",
    description: "用于控制视频播放和导航的快捷键",
  },
  {
    id: "timeseries",
    title: "时间序列控制",
    description: "用于操作时间序列数据区域的快捷键",
  },
  {
    id: "image_gallery",
    title: "图片集导航",
    description: "用于在多图任务中切换图片的快捷键",
  },
  {
    id: "paragraphs",
    title: "段落导航",
    description: "用于在段落或对话视图中浏览句子和区域的快捷键",
  },
];

export const DEFAULT_HOTKEYS = BASE_DEFAULT_HOTKEYS.map((hotkey) => ({
  ...hotkey,
  ...(HOTKEY_TRANSLATIONS[hotkey.element] ?? {}),
}));

export const HOTKEY_SECTIONS = BASE_HOTKEY_SECTIONS;

/**
 * URL patterns mapped to their corresponding hotkey sections
 * Used to automatically determine which shortcuts to display based on current page
 */
export const URL_TO_SECTION_MAPPING = [
  {
    regex: /\/projects\/\d+\/data\/?\?.*task=\d+/i,
    section: ["annotation", "regions"],
  },
  {
    regex: /\/projects\/\d+\/data\/?$/i,
    section: "data_manager",
  },
];
